---
title: "Untitled"
output: html_document
---

```{r}
library(tidyverse)
library(here)

theme_set(theme_bw())
```

```{r}
df_stories = read_csv(here("models/01_nlu_project/model_visualization/testing_data/tokenized_stories.csv"))
  
df_attention = read_csv(here("models/01_nlu_project/model_visualization/testing_data/attention.csv"))

df_loss = read_csv(here("models/01_nlu_project/model_visualization/testing_data/loss.csv")) %>% 
  arrange(loss) %>% 
  mutate(reordered_story_id = row_number())

df = left_join(df_stories, df_attention, by=c("tensor","story_id", "token_id")) %>% 
  select(-tensor) %>% 
  left_join(., df_loss, by=c("story_id")) %>% 
  arrange(loss) 
  # select(-story_id)
```

# paper attention visualizations

```{r}
df_plot = df %>% 
  filter(reordered_story_id == 5 | reordered_story_id == 6 | reordered_story_id == 10)
  # filter(reordered_story_id == 6)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

x_labels <- function(v) {
  str_replace_all(v, "_.*", "")
}

test_plot = ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  # geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  xlab("Tokenized story") +
  ylab("Attention weights") +
  facet_wrap(~reordered_story_id, scales = "free", nrow=6) +
  theme(axis.title = element_text(size = 14, color="#3c3c3c")) +
  theme(axis.title.x = element_text(margin = margin(t = 7, r = 0, b = 0, l = 0))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 7, b = 0, l = 0))) +
  theme(axis.text = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  scale_x_discrete(labels= x_labels)

test_plot


ggsave(here("writing/2019_SCiL/graphs/attention-viz.pdf"),test_plot,height=7,width=9)
# ggsave(filename="attention_viz1.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 24, width = 38)
```

# additional attention visualizations

```{r}
df_plot = df %>% 
  filter(reordered_story_id < 19)
  # filter(reordered_story_id < 37)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

df_text = df_plot %>% 
  select(target,prediction,reordered_story_id) %>% 
  gather(measure,value,target,prediction) %>% 
  distinct() %>% 
  mutate(y = ifelse(measure=="target",-Inf,Inf),
         hjust = ifelse(measure=="target",-1,1)) %>% 
  mutate_at(vars(value), funs(round(.,3))) %>% 
  mutate(label = paste(measure,value,sep=": "))

x_labels <- function(v) {
  str_replace_all(v, "_.*", "")
}

test_plot = ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~reordered_story_id, scales = "free", nrow=6) +
  geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)

ggsave(filename="attention_viz1.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 24, width = 38)
```


```{r}
df_plot = df %>% 
  filter(reordered_story_id == 5)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

df_text = df_plot %>% 
  select(target,prediction,reordered_story_id) %>% 
  gather(measure,value,target,prediction) %>% 
  distinct() %>% 
  mutate(y = ifelse(measure=="target",-Inf,Inf),
         hjust = ifelse(measure=="target",-1,1)) %>% 
  mutate_at(vars(value), funs(round(.,3))) %>% 
  mutate(label = paste(measure,value,sep=": "))

x_labels <- function(v) {
  str_replace_all(v, "_.*", "")
}

ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)

test_plot

# ggsave(filename="attention_weights2.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 24, width = 38)
```

```{r}
df_complexavg = df %>% 
  group_by(story_id) %>% 
  arrange(-attention) %>% 
  mutate(num_tokens = n()) %>% 
  mutate(relevance_pos = seq.int(num_tokens)) %>% 
  ungroup() %>% 
  mutate(relevant = ifelse(relevance_pos < (num_tokens*0.1), 1, 0)) %>% 
  group_by(story_tokenized) %>% 
  summarize(avgRelevance = mean(relevant), occurrences = n()) %>% 
  arrange(-avgRelevance) %>% 
  filter(avgRelevance > 0) %>% 
  filter(occurrences > 1)

df_complexavg

plot=ggplot(df_complexavg, aes(x=reorder(story_tokenized,-avgRelevance), y=avgRelevance)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_simpleavg = df %>% 
  group_by(story_tokenized) %>% 
  summarize(avgAttention = mean(attention), occurrences = n()) %>% 
  arrange(-avgAttention) %>% 
  # filter(occurrences > 1) %>% 
  head(n=50)

df_simpleavg

plot=ggplot(df_simpleavg, aes(x=reorder(story_tokenized,-avgAttention), y=avgAttention)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_orig = read_csv(here("models/01_nlu_project/data/data_prep/suspect_guilt_testing.csv"))

hedges = c("about", "actually", "allege", "almost", "appear to be", "apparently", "approximately", "around", "assume", "at least", "believe", "could", "doubt", "estimate", "few", "frequently", "generally", "if", "indicate", "kind of", "kinda", "largely", "little", "like", "look like", "mainly", "may", "might", "mostly", "nearly", "occasionally", "over", "partially", "perhaps", "possibility", "possibly", "probably", "quite", "rather", "roughly", "seem", "should", "somehow", "sometimes", "somewhat", "sort of", "sorta", "speculate", "suggest", "supposedly", "sure", "tend", "think", "up to", "vaguely", "virtually", "would")

h_str = str_c(hedges, collapse = "|")

df_h = df_orig %>% 
  mutate(hedgeMention = str_count(story_reproduction, h_str)) %>% 
  arrange(-hedgeMention)

df_nh = df_h %>%
  mutate_at(vars(story_reproduction), funs(str_replace_all(.,h_str,""))) %>% 
  mutate(newhedgeMention = str_count(story_reproduction, h_str))

new_df = df_h
```





# Bees jail

```{r}
df_stories = read_csv(here("models/01_nlu_project/model_visualization/bees_jail_data/tokenized_stories.csv"))
  
df_attention = read_csv(here("models/01_nlu_project/model_visualization/bees_jail_data/attention.csv"))

df_loss = read_csv(here("models/01_nlu_project/model_visualization/bees_jail_data/loss.csv")) %>% 
  arrange(loss) %>% 
  mutate(reordered_story_id = row_number())

df = left_join(df_stories, df_attention, by=c("tensor","story_id", "token_id")) %>% 
  select(-tensor) %>% 
  left_join(., df_loss, by=c("story_id")) %>% 
  arrange(loss) 
  # select(-story_id)
```
```{r}
df_plot = df %>% 
  filter(chain == 0)
  # filter(reordered_story_id < 37)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

df_text = df_plot %>% 
  select(target,prediction,generation) %>% 
  gather(measure,value,target,prediction) %>% 
  distinct() %>% 
  mutate(y = ifelse(measure=="target",-Inf,Inf),
         hjust = ifelse(measure=="target",-1,1)) %>% 
  mutate_at(vars(value), funs(round(.,3))) %>% 
  mutate(label = paste(measure,value,sep=": "))

plot_gen0 = ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  # facet_wrap(~generation, scales = "free", nrow=6) +
  geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(filename="gen0_beesjail.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 7, width = 25)
```

```{r}
df_plot = df %>% 
  filter(chain == "wo572d9yYwv41dUF")
  # filter(reordered_story_id < 37)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

df_text = df_plot %>% 
  select(target,prediction,generation) %>% 
  gather(measure,value,target,prediction) %>% 
  distinct() %>% 
  mutate(y = ifelse(measure=="target",-Inf,Inf),
         hjust = ifelse(measure=="target",-1,1)) %>% 
  mutate_at(vars(value), funs(round(.,3))) %>% 
  mutate(label = paste(measure,value,sep=": "))

plot_repros = ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~generation, scales = "free", nrow=5) +
  geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(filename="gen_other_beesjail.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 20, width = 7)
```


# Bees free

```{r}
df_stories = read_csv(here("models/01_nlu_project/model_visualization/bees_free_data/tokenized_stories.csv"))
  
df_attention = read_csv(here("models/01_nlu_project/model_visualization/bees_free_data/attention.csv"))

df_loss = read_csv(here("models/01_nlu_project/model_visualization/bees_free_data/loss.csv")) %>% 
  arrange(loss) %>% 
  mutate(reordered_story_id = row_number())

df = left_join(df_stories, df_attention, by=c("tensor","story_id", "token_id")) %>% 
  select(-tensor) %>% 
  left_join(., df_loss, by=c("story_id")) %>% 
  arrange(loss) 
  # select(-story_id)
```

```{r}
df_plot = df %>% 
  filter(chain == 0)
  # filter(reordered_story_id < 37)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

df_text = df_plot %>% 
  select(target,prediction,generation) %>% 
  gather(measure,value,target,prediction) %>% 
  distinct() %>% 
  mutate(y = ifelse(measure=="target",-Inf,Inf),
         hjust = ifelse(measure=="target",-1,1)) %>% 
  mutate_at(vars(value), funs(round(.,3))) %>% 
  mutate(label = paste(measure,value,sep=": "))

plot_gen0 = ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  # facet_wrap(~generation, scales = "free", nrow=6) +
  geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(filename="gen0_beesfree.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 7, width = 25)
```

```{r}
df_plot = df %>% 
  filter(chain == "fmqv2eegACZcA9lj")
  # filter(reordered_story_id < 37)

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

df_text = df_plot %>% 
  select(target,prediction,generation) %>% 
  gather(measure,value,target,prediction) %>% 
  distinct() %>% 
  mutate(y = ifelse(measure=="target",-Inf,Inf),
         hjust = ifelse(measure=="target",-1,1)) %>% 
  mutate_at(vars(value), funs(round(.,3))) %>% 
  mutate(label = paste(measure,value,sep=": "))

plot_repros = ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~generation, scales = "free", nrow=5) +
  geom_text(data=df_text,aes(x=-Inf,y=y,vjust=hjust,label=label),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(filename="gen_other_beesfree.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 20, width = 7)
```



# Hedges

```{r}
df_stories = read_csv(here("models/01_nlu_project/model_visualization/hedges/tokenized_stories.csv"))
  
df_attention = read_csv(here("models/01_nlu_project/model_visualization/hedges/attention.csv"))

df_pred = read_csv(here("models/01_nlu_project/model_visualization/hedges/loss.csv")) 

df = left_join(df_stories, df_attention, by=c("tensor","story_id", "token_id")) %>% 
  select(-tensor) %>% 
  left_join(., df_pred, by=c("story_id"))

df_stories = read_csv(here("models/01_nlu_project/model_visualization/noev_hedges/tokenized_stories.csv"))
  
df_attention = read_csv(here("models/01_nlu_project/model_visualization/noev_hedges/attention.csv"))

df_pred = read_csv(here("models/01_nlu_project/model_visualization/noev_hedges/loss.csv")) 

df_noev = left_join(df_stories, df_attention, by=c("tensor","story_id", "token_id")) %>% 
  select(-tensor) %>% 
  left_join(., df_pred, by=c("story_id"))

df = df %>% 
  bind_rows(df_noev)
```

```{r}

toplot = df %>% 
  select(story_cond, hedges, prediction) %>% 
  distinct() %>% 
  mutate(condition = ifelse(str_detect(story_cond,"jail"), 
                            "strong evidence", 
                            ifelse(str_detect(story_cond,"free"),
                                   "weak evidence",
                                   "no evidence"))) %>% 
  mutate(topic = ifelse(str_detect(story_cond,"jail"), 
                        str_replace_all(story_cond,"_jail",""), 
                        ifelse(str_detect(story_cond,"free"),
                               str_replace_all(story_cond,"_free",""),
                               str_replace_all(story_cond, "_noev","")))) %>% 
  mutate_at(vars(condition), funs(fct_relevel(., "strong evidence", "weak evidence", "no evidence"))) %>% 
  mutate_at(vars(hedges), funs(ifelse(hedges, "with", "no"))) %>% 
  mutate_at(vars(hedges), funs(fct_relevel(., "with", "no")))

ggplot(toplot, aes(x=hedges, y=prediction, color=topic, group=topic)) +
# ggplot(toplot, aes(x=hedges, y=prediction)) +
  facet_wrap(~condition) +
  geom_point(alpha=0.7) +
  geom_line() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(angle=30, hjust=1)) +
  xlab("Hedges") +
  ylab("Prediction") +
  # stat_summary(fun.y = "mean",
  #              geom = "point",
  #              size = 4) +
  # stat_summary(fun.data = mean_cl_boot,
  #              geom = "errorbar",
  #              width = 0.1)
  ggsave(here("writing/2019_SCiL/graphs/hedges.pdf"),height=4,width=4.5)

  
```

```{r}
df_plot = df %>% 
  # filter(str_detect(story_cond,"jail")) %>% 
  mutate(fac_col = ifelse(hedges, str_c(story_cond, "withHedges", sep="_"), str_c(story_cond, "noHedges", sep="_")))

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

x_labels <- function(v) {
  str_replace_all(v, "_.*", "")
}

# ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
#   geom_line() +
#   facet_wrap(~fac_col, scales = "free", ncol=2) +
#   geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#   scale_x_discrete(labels= x_labels)
# 
# ggsave(filename="hedges_att_jail.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 20, width = 38)

ggplot(df_plot[str_detect(df_plot$story_cond, "arson"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~fac_col, scales = "free", ncol=2) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_arson.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 9, width = 35)

ggplot(df_plot[str_detect(df_plot$story_cond, "bees"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~fac_col, scales = "free", ncol=2) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_bees.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 9, width = 35)

ggplot(df_plot[str_detect(df_plot$story_cond, "professor"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~fac_col, scales = "free", ncol=2) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_professor.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 9, width = 35)

ggplot(df_plot[str_detect(df_plot$story_cond, "scam"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~fac_col, scales = "free", ncol=2) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_scam.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 9, width = 35)

ggplot(df_plot[str_detect(df_plot$story_cond, "smuggler"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~fac_col, scales = "free", ncol=2) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_smuggler.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 9, width = 35)
```

```{r}
df_plot = df %>% 
  filter(str_detect(story_cond,"free")) %>% 
  mutate(fac_col = ifelse(hedges, str_c(story_cond, "withHedges", sep="_"), str_c(story_cond, "noHedges", sep="_")))

df_plot$xaxis = paste(df_plot$story_tokenized,df_plot$token_id,sep="_")
df_plot$xaxis = reorder(df_plot$xaxis, df_plot$token_id)

x_labels <- function(v) {
  str_replace_all(v, "_.*", "")
}

ggplot(df_plot, aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~fac_col, scales = "free", ncol=2) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)

ggsave(filename="hedges_att_jail.png",path=here("models","01_nlu_project","model_visualization","graphs"), height = 20, width = 38)

ggplot(df_plot[str_detect(df_plot$story_cond, "arson"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~hedges, scales = "free", ncol=1) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_arsonjail.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 5, width = 20)

ggplot(df_plot[str_detect(df_plot$story_cond, "bees"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~hedges, scales = "free", ncol=1) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_beesjail.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 5, width = 20)

ggplot(df_plot[str_detect(df_plot$story_cond, "professor"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~hedges, scales = "free", ncol=1) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_profjail.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 5, width = 20)

ggplot(df_plot[str_detect(df_plot$story_cond, "scam"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~hedges, scales = "free", ncol=1) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_scamjail.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 5, width = 20)

ggplot(df_plot[str_detect(df_plot$story_cond, "smuggler"),], aes(x=xaxis,y=attention, group = 1)) +
  geom_line() +
  facet_wrap(~hedges, scales = "free", ncol=1) +
  geom_text(aes(x=-Inf,y=-Inf,vjust=-1,label=prediction),hjust=0) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels= x_labels)+
  ggsave(filename="hedges_att_smugglerjail.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 5, width = 20)
```

# Hedges - no evidence

```{r}
df_stories = read_csv(here("models/01_nlu_project/model_visualization/noev_hedges/tokenized_stories.csv"))
  
df_attention = read_csv(here("models/01_nlu_project/model_visualization/noev_hedges/attention.csv"))

df_pred = read_csv(here("models/01_nlu_project/model_visualization/noev_hedges/loss.csv")) 

df = left_join(df_stories, df_attention, by=c("tensor","story_id", "token_id")) %>% 
  select(-tensor) %>% 
  left_join(., df_pred, by=c("story_id"))
  # select(-story_id)
```

```{r}

toplot = df %>% 
  select(story_cond, hedges, prediction) %>% 
  distinct() %>% 
  mutate(topic = str_replace_all(story_cond,"_noev",""))

ggplot(toplot, aes(x=hedges, y=prediction, color=topic, group=topic)) +
# ggplot(toplot, aes(x=hedges, y=prediction)) +
  # facet_wrap(~condition) +
  geom_point(alpha=0.7) +
  geom_line() +
  # stat_summary(fun.y = "mean",
  #              geom = "point",
  #              size = 4) +
  # stat_summary(fun.data = mean_cl_boot,
  #              geom = "errorbar",
  #              width = 0.1)
  ggsave(filename="hedges_overview_noev.png", path=here("models", "01_nlu_project", "model_visualization", "graphs"), height = 3, width = 5)

# library(lme4)
# library(lmerTest)
# 
# m = lmer(prediction ~ condition * hedges + (1 | story_cond), data=toplot)
# summary(m)
  
```






