---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
df = read_csv(here("losses.csv"))
df2 = read_csv(here("losses.csv"))
```

```{r}
ggplot(df,aes(x=Epoch,y=Loss,color=Data_type,fill=Data_type)) +
  # geom_point(alpha=0.2, position="jitter") +
  # error bars 
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               size = 1) + 
  # # median
  # stat_summary(fun.y = "median",
  #              geom = "point",
  #              shape = 21,
  #              size = 4) +
  # means
  stat_summary(fun.y = "mean",
               geom = "point",
               shape = 21,
               size = 4)
  # ylim(0,0.05)
```

```{r}
ggplot(df2,aes(x=Epoch,y=Loss,color=Data_type,fill=Data_type)) +
  # geom_point(alpha=0.2, position="jitter") +
  # error bars 
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               size = 1) + 
  # # median
  # stat_summary(fun.y = "median",
  #              geom = "point",
  #              shape = 21,
  #              size = 4) +
  # means
  stat_summary(fun.y = "mean",
               geom = "point",
               shape = 21,
               size = 4)
  # ylim(0,0.05)
```